language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE albumfindertests;' -U postgres
deploy:
  api_key:
    secure: 4vf66dy1eyC/CrMYcsFGtBBtvHYplbsRAZk46GXee95fXqAhqv70aclu/K6VdFCerJKdquayqsW9hA0aVw6sylPacOayoCX8QBJE0+cnUyVAsrmJ9r5EGMhEFbgGBGT7kJAT8mdzIbVibhigLW56OwTIn5XYep91djZnlsjNfLzEeKpsqyXQgdwzLJX5OA5xd7Sa5f7lLWZsBzg4EH3AWQMqhELwvug3KHof2l6UlHnceOUJ8xNM9thPVwPRK5KhV2etXhPSxY/au0ypyZ6BTU7kVmbA5k9cMs3yKIb9dTv48sB5Z74oFdhJrgzLpcKzLO+yRIoNp2IlSMZ3A74mn+HG1qdTioLcUeYc58DD6p7BWrzw3n71ONLwOKcicLYWiHIN+DPKahOr+E4c5A3EvCZoZB27JYnVyUCZnz+p/dIqZ0r3NYHCpAScH1gpn51HhII+jgJJtg/ZtW665Hm3l3QhuhR4QYrdI677T/s//M2RYBURHBdNG4CAggD20FqUirJijvB6EgGTeyi7TfxqrMfSz85/o3OGwIE7ngXAQ6Tb6iq1AQPA3n1AdACoKff1naSVQzVbAH1JjYDz2RDddfk/eczIKZqf6pkMAIkl/oqQ0+rnELNWnaXq/M2223CAKGAo+HMEHuwuT8zt51b7pO2zV1lHCTdY3IDHeAL4vR0=
